### ISSUE TITLE
Removed?

### ISSUE THREAD

**Issue by Tombo89** [komoot/BLEConnect#7]
Hello,
i found this site earlyer this year and was ver interested in this function. I startet building a Diy Display solution so that there is no need to put my Smartphone on my bike. I had all working but wanted to fix some little coding errors. Now i come back and see you changed everything. I Have 2 options in the List of comoot for connecting to Yamaha and Flyer but i cant connect to my builded device anymore. Is there any fix for this?

**Comment by danielgard** [comment]
Hey @Tombo89 !

Good to hear that you build something cool with the connect API! 
We changed the UI in our app since we'll enhance the BLE interface more in future. At the moment there is no general entry for "bluetooth device" anymore. But the functionality is still the same when you select "Flyer Bike".

With that you should be able to connect your device again. Let me know if it works and i would be interested to know more about your project! 

Best
Daniel
